vim.opt.number = true
vim.opt.numberwidth = 3
vim.opt.mouse = ''
vim.opt.softtabstop = 4
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.o.foldcolumn = '1'
vim.o.foldlevel = 99
vim.o.foldlevelstart = 99
vim.o.foldenable = true
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.termguicolors = true
-- vim.opt.list = true
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
vim.g.strip_whitespace_on_save = 1
vim.o.sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
