alias dotfiles='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias cook='cookiecutter https://github.com/alexismanuel/forge.git --directory'
alias dtf='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias vim='nvim'
alias v='vim .'
alias drm='docker ps -qa | xargs -r docker rm -f'
