require('keymaps')
require('options')
require('plugins/lazy')
require('plugins/lualine')
require('plugins/autoclose')
require('plugins/nvim-tree')
require('plugins/telescope')
require('plugins/nvim-treesitter')
require('plugins/cmp')
require('plugins/lsp-zero')
require('plugins/mason-lspconfig')
require('plugins/toggleterm')
require('plugins/ufo')
-- require('plugins/diffview')
require('commands')

